# Generated by Django 6.0.7 on 2026-09-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity',
            field=models.CharField(choices=[('School', 'School'), ('House', 'House'), ('Student', 'Student'), ('Category', 'Category'), ('Event', 'Event'), ('Registration', 'Registration'), ('Result', 'Result'), ('User', 'User')], max_length=30),
        ),
    ]
